### ISSUE TITLE
Why not semantic versioning?

### ISSUE THREAD

**Issue by Fleischers** [nick-nikoliuk/webGLEngine#1]
Take a look for semantic versioning rules http://semver.org/
According to it, you should consider using 3 numbers like 0.2.0 instead of just 0.2

**Comment by mykola-nikoliuk** [comment]
Thanks for your remark.
Both releases were fixed.
The next build will be created with considering semantic versioning rules.

**Comment by Fleischers** [comment]
@nick-nikoliuk By the way, you could create tags with `git tag` and then `git push --tags`. it may be usable if you want create big releases by hand in github and small bugfixes just by marking with updated patch number.
Personally I prefer using `npm version` command where applicable to automatically update package.json version and git tags
